memberlist_page:
    base-function: get_All_patient_summary
    system-intent:
        functions: 
          - get_All_patient_summary
        options:
            patient_summary: Patient Summary
            next_best_action: Next Best Action                        
    user-intent:
        functions:
          - web_search

landing_page:
    base-function: get_Patient_Summary
    system-intent:
        functions: 
          - get_Patient_Summary
        options:
            patient_summary: Patient Summary
            next_best_action: Next Best Action            
            insights: Insights
            voice_note: Voice Note
    user-intent:
         functions:
          - web_search

order_page:
    base-function: get_Patient_Summary
    system-intent:
        auto_populate:
            functions: 
              - get_Patient_Summary
        options:            
            next_best_action: Next Best Action
            auto_populate: Auto Populate
    user-intent:
        functions:
        - getPatientVitals
        - web_search
        
consent_page:
    base-function: get_Patient_Summary
    system-intent:
        auto_populate:
            functions:           
              - get_advanced_care_plan
              - get_Responsible_party
        options:            
            auto_populate: Auto Populate
            insights: Insights            
    user-intent:
        functions:           
          - get_advanced_care_plan
          - get_Responsible_party 
          - web_search

